#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

curr_user:
  path: /api/curr_user
  controller: App\Controller\AuthController::getCurrUser

login_check:
  path:     /login_check
  methods:  [POST]
